name = "codepedia"
main = "worker.js"
compatibility_date = "2024-06-22"

[[routes]]
pattern = "*.codepedia.space/*"
zone_id = "b92fe6de8e9f5492b9d581b597bb2854"

[[d1_databases]]
binding = "DB"
database_name = "codepedia-users"
database_id = "0a79d382-e939-454a-86c8-395a27beaaf3"
