name = "codepedia"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# База данных D1
[[d1_databases]]
binding = "DB"
database_name = "codepedia_db"
database_id = "32105466-1de8-49be-8709-6da695448235"

# Переменные окружения
[vars]
NODE_ENV = "production"
APP_NAME = "CodePedia"

[env.production]
vars = { NODE_ENV = "production" }

[env.preview]
vars = { NODE_ENV = "development" }

# Маршруты
routes = [
   { pattern = "codepedia.space/*", zone_id = "b92fe6de8e9f5492b9d581b597bb2854" }
]

# Статика из корня
[assets]
directory = "./"
binding = "ASSETS"

[observability]
logs = { enable = true }
